export const SAMPLE_PROFILE_DEFAULT = "baseline-barry";
export const SAMPLE_PROFILE_VERSION = 2;

export const SAMPLE_PROFILES = Object.freeze({
  "baseline-barry": {
    name: "Barry",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 7.6,
      meanEnd: 7.6,
      sdHours: 0.35,
      weekendDelta: 0.45,
      minHours: 5.5,
      maxHours: 9.2,
      wakeWeekday: { hour: 6, minute: 45 },
      wakeWeekend: { hour: 7, minute: 35 },
      wakeJitterMin: 14,
      respirationBase: 15.2,
    },
    rhr: {
      baseStart: 56,
      baseEnd: 56,
      sd: 1.2,
      poorSleepBpmDelta: 2.0,
      prevLoadBpmPerHour: 0.8,
      time: { hour: 7, minute: 45 },
    },
    nutrition: {
      caloriesStart: 2400,
      caloriesEnd: 2400,
      sdCalories: 150,
      weekendDelta: 160,
      minCalories: 1700,
      maxCalories: 3200,
      proteinStart: 140,
      proteinEnd: 140,
      sdProtein: 10,
      minProtein: 70,
      maxProtein: 220,
      fatStart: 85,
      fatEnd: 85,
      sdFat: 8,
      minFat: 40,
      maxFat: 140,
      minCarbs: 80,
      maxCarbs: 520,
      sugarBase: 35,
      sugarSd: 10,
      poorSleepSugarDelta: 14,
      time: { hour: 19, minute: 0 },
    },
    bp: {
      sysStart: 118,
      sysEnd: 118,
      diaStart: 76,
      diaEnd: 76,
      sdSys: 4,
      sdDia: 3,
      poorSleepSysDelta: 2,
      poorSleepDiaDelta: 1,
      time: { hour: 8, minute: 25 },
    },
    weight: {
      lbStart: 182,
      lbEnd: 182,
      follow: 0.25,
      sd: 0.25,
      workoutFactor: 0.25,
      time: { hour: 7, minute: 10 },
    },
    steps: {
      baseStart: 8200,
      baseEnd: 8600,
      sd: 1400,
      workoutBonus: 1200,
      time: { hour: 21, minute: 30 },
    },
    exercise: {
      weekdays: [1, 3, 6], // Mon/Wed/Sat
      activities: ["Strength", "Run", "Cycling"],
      durationStart: 45,
      durationEnd: 55,
      sdMinutes: 10,
      caloriesPerMin: 8.2,
      easyPct: 0.1,
      hardPct: 0.2,
      maxWorkoutsPerDay: 1,
      startHour: 17,
      startMinute: 45,
    },
  },

  "weightloss-wally": {
    name: "Wally",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 7.0,
      meanEnd: 7.2,
      sdHours: 0.45,
      weekendDelta: 0.5,
      minHours: 5.2,
      maxHours: 9.0,
      wakeWeekday: { hour: 6, minute: 30 },
      wakeWeekend: { hour: 7, minute: 40 },
      wakeJitterMin: 16,
      respirationBase: 15.6,
    },
    rhr: {
      baseStart: 61,
      baseEnd: 58,
      sd: 1.6,
      poorSleepBpmDelta: 2.3,
      prevLoadBpmPerHour: 1.0,
      time: { hour: 7, minute: 40 },
    },
    nutrition: {
      caloriesStart: 2750,
      caloriesEnd: 2550,
      sdCalories: 200,
      weekendDelta: 450,
      minCalories: 1800,
      maxCalories: 4200,
      proteinStart: 160,
      proteinEnd: 155,
      sdProtein: 12,
      minProtein: 90,
      maxProtein: 230,
      fatStart: 75,
      fatEnd: 70,
      sdFat: 10,
      minFat: 40,
      maxFat: 130,
      minCarbs: 90,
      maxCarbs: 450,
      sugarBase: 38,
      sugarSd: 12,
      poorSleepSugarDelta: 16,
      time: { hour: 19, minute: 10 },
    },
    bp: {
      sysStart: 126,
      sysEnd: 121,
      diaStart: 82,
      diaEnd: 79,
      sdSys: 5,
      sdDia: 3,
      poorSleepSysDelta: 2,
      poorSleepDiaDelta: 1,
      time: { hour: 8, minute: 20 },
    },
    weight: {
      lbStart: 210,
      lbEnd: 204,
      follow: 0.24,
      sd: 0.28,
      workoutFactor: 0.35,
      time: { hour: 7, minute: 15 },
    },
    steps: {
      baseStart: 8600,
      baseEnd: 9800,
      sd: 1500,
      workoutBonus: 1700,
      time: { hour: 21, minute: 35 },
    },
    exercise: {
      weekdays: [1, 3, 5], // Mon/Wed/Fri
      activities: ["Strength", "Cycling", "Walk"],
      durationStart: 40,
      durationEnd: 55,
      sdMinutes: 12,
      caloriesPerMin: 7.9,
      easyPct: 0.15,
      hardPct: 0.22,
      maxWorkoutsPerDay: 1,
      startHour: 17,
      startMinute: 30,
    },
  },

  "athlete-anna": {
    name: "Anna",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 7.9,
      meanEnd: 8.1,
      sdHours: 0.3,
      weekendDelta: 0.35,
      minHours: 6.4,
      maxHours: 9.4,
      wakeWeekday: { hour: 6, minute: 15 },
      wakeWeekend: { hour: 7, minute: 20 },
      wakeJitterMin: 12,
      respirationBase: 14.6,
    },
    rhr: {
      baseStart: 54,
      baseEnd: 53,
      sd: 1.0,
      poorSleepBpmDelta: 1.8,
      prevLoadBpmPerHour: 1.2,
      time: { hour: 7, minute: 20 },
    },
    nutrition: {
      caloriesStart: 2600,
      caloriesEnd: 2850,
      sdCalories: 180,
      weekendDelta: 160,
      minCalories: 1900,
      maxCalories: 3600,
      proteinStart: 180,
      proteinEnd: 210,
      sdProtein: 12,
      minProtein: 120,
      maxProtein: 300,
      fatStart: 78,
      fatEnd: 85,
      sdFat: 9,
      minFat: 45,
      maxFat: 150,
      minCarbs: 130,
      maxCarbs: 600,
      sugarBase: 30,
      sugarSd: 10,
      poorSleepSugarDelta: 12,
      time: { hour: 18, minute: 40 },
    },
    bp: {
      sysStart: 116,
      sysEnd: 115,
      diaStart: 74,
      diaEnd: 73,
      sdSys: 4,
      sdDia: 3,
      poorSleepSysDelta: 1,
      poorSleepDiaDelta: 1,
      time: { hour: 8, minute: 10 },
    },
    weight: {
      lbStart: 145,
      lbEnd: 145,
      follow: 0.3,
      sd: 0.22,
      workoutFactor: 0.25,
      time: { hour: 7, minute: 5 },
    },
    steps: {
      baseStart: 9500,
      baseEnd: 11200,
      sd: 1700,
      workoutBonus: 1800,
      time: { hour: 21, minute: 25 },
    },
    exercise: {
      weekdays: [1, 2, 4, 5, 6], // Mon/Tue/Thu/Fri/Sat
      activities: ["Run", "Strength", "Cycling", "Intervals", "Mobility"],
      durationStart: 55,
      durationEnd: 75,
      sdMinutes: 12,
      caloriesPerMin: 9.2,
      easyPct: 0.15,
      hardPct: 0.35,
      maxWorkoutsPerDay: 2,
      startHour: 17,
      startMinute: 35,
    },
  },

  "protein-paul": {
    name: "Paul",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 7.45,
      meanEnd: 7.55,
      sdHours: 0.4,
      weekendDelta: 0.3,
      minHours: 5.3,
      maxHours: 9.1,
      wakeWeekday: { hour: 6, minute: 50 },
      wakeWeekend: { hour: 7, minute: 30 },
      wakeJitterMin: 15,
      respirationBase: 15.0,
    },
    rhr: {
      baseStart: 58,
      baseEnd: 56,
      sd: 1.3,
      poorSleepBpmDelta: 2.1,
      prevLoadBpmPerHour: 0.9,
      time: { hour: 7, minute: 50 },
    },
    nutrition: {
      caloriesStart: 2550,
      caloriesEnd: 2550,
      sdCalories: 180,
      weekendDelta: 200,
      minCalories: 1700,
      maxCalories: 3800,
      proteinStart: 70,
      proteinEnd: 75,
      sdProtein: 10,
      minProtein: 35,
      maxProtein: 160,
      fatStart: 90,
      fatEnd: 92,
      sdFat: 12,
      minFat: 45,
      maxFat: 160,
      minCarbs: 110,
      maxCarbs: 520,
      sugarBase: 42,
      sugarSd: 14,
      poorSleepSugarDelta: 10,
      time: { hour: 19, minute: 5 },
    },
    bp: {
      sysStart: 122,
      sysEnd: 120,
      diaStart: 78,
      diaEnd: 77,
      sdSys: 4,
      sdDia: 3,
      poorSleepSysDelta: 2,
      poorSleepDiaDelta: 1,
      time: { hour: 8, minute: 22 },
    },
    weight: {
      lbStart: 176,
      lbEnd: 176,
      follow: 0.23,
      sd: 0.3,
      workoutFactor: 0.3,
      time: { hour: 7, minute: 12 },
    },
    steps: {
      baseStart: 8000,
      baseEnd: 9000,
      sd: 1400,
      workoutBonus: 1300,
      time: { hour: 21, minute: 30 },
    },
    exercise: {
      weekdays: [2, 4, 6], // Tue/Thu/Sat
      activities: ["Strength", "Run", "Cycling"],
      durationStart: 35,
      durationEnd: 50,
      sdMinutes: 12,
      caloriesPerMin: 7.8,
      easyPct: 0.14,
      hardPct: 0.2,
      maxWorkoutsPerDay: 1,
      startHour: 17,
      startMinute: 40,
    },
  },

  "hypertension-holly": {
    name: "Holly",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 7.1,
      meanEnd: 7.25,
      sdHours: 0.5,
      weekendDelta: 0.4,
      minHours: 5.0,
      maxHours: 9.4,
      wakeWeekday: { hour: 6, minute: 35 },
      wakeWeekend: { hour: 7, minute: 45 },
      wakeJitterMin: 18,
      respirationBase: 15.8,
    },
    rhr: {
      baseStart: 62,
      baseEnd: 60,
      sd: 1.7,
      poorSleepBpmDelta: 2.5,
      prevLoadBpmPerHour: 1.1,
      time: { hour: 7, minute: 55 },
    },
    nutrition: {
      caloriesStart: 2600,
      caloriesEnd: 2500,
      sdCalories: 250,
      weekendDelta: 300,
      minCalories: 1700,
      maxCalories: 4200,
      proteinStart: 120,
      proteinEnd: 125,
      sdProtein: 14,
      minProtein: 55,
      maxProtein: 200,
      fatStart: 95,
      fatEnd: 90,
      sdFat: 14,
      minFat: 40,
      maxFat: 170,
      minCarbs: 90,
      maxCarbs: 560,
      sugarBase: 45,
      sugarSd: 16,
      poorSleepSugarDelta: 12,
      time: { hour: 19, minute: 15 },
    },
    bp: {
      sysStart: 150,
      sysEnd: 142,
      diaStart: 92,
      diaEnd: 88,
      sdSys: 7,
      sdDia: 5,
      poorSleepSysDelta: 4,
      poorSleepDiaDelta: 2,
      time: { hour: 8, minute: 10 },
    },
    weight: {
      lbStart: 195,
      lbEnd: 193,
      follow: 0.22,
      sd: 0.35,
      workoutFactor: 0.25,
      time: { hour: 7, minute: 18 },
    },
    steps: {
      baseStart: 6400,
      baseEnd: 7200,
      sd: 1500,
      workoutBonus: 900,
      time: { hour: 21, minute: 25 },
    },
    exercise: {
      weekdays: [2, 5], // Tue/Fri
      activities: ["Walk", "Cycling", "Strength"],
      durationStart: 25,
      durationEnd: 40,
      sdMinutes: 12,
      caloriesPerMin: 6.9,
      easyPct: 0.22,
      hardPct: 0.12,
      maxWorkoutsPerDay: 1,
      startHour: 16,
      startMinute: 50,
    },
  },

  "chronic-chloe": {
    name: "Chloe",
    sources: {
      sleep: "Wearable",
      workout: "Training App",
      nutrition: "Food Log",
      bp: "BP Cuff",
      weight: "Smart Scale",
    },
    sleep: {
      meanStart: 6.6,
      meanEnd: 6.9,
      sdHours: 0.75,
      weekendDelta: 0.6,
      minHours: 4.2,
      maxHours: 9.0,
      wakeWeekday: { hour: 6, minute: 25 },
      wakeWeekend: { hour: 7, minute: 35 },
      wakeJitterMin: 20,
      respirationBase: 16.2,
    },
    rhr: {
      baseStart: 66,
      baseEnd: 63,
      sd: 2.4,
      poorSleepBpmDelta: 3.0,
      prevLoadBpmPerHour: 1.2,
      time: { hour: 7, minute: 55 },
    },
    nutrition: {
      caloriesStart: 2800,
      caloriesEnd: 2700,
      sdCalories: 320,
      weekendDelta: 550,
      minCalories: 1600,
      maxCalories: 4600,
      proteinStart: 115,
      proteinEnd: 120,
      sdProtein: 16,
      minProtein: 45,
      maxProtein: 210,
      fatStart: 95,
      fatEnd: 90,
      sdFat: 18,
      minFat: 35,
      maxFat: 190,
      minCarbs: 100,
      maxCarbs: 700,
      sugarBase: 55,
      sugarSd: 22,
      poorSleepSugarDelta: 18,
      time: { hour: 19, minute: 20 },
    },
    bp: {
      sysStart: 130,
      sysEnd: 128,
      diaStart: 84,
      diaEnd: 82,
      sdSys: 6,
      sdDia: 4,
      poorSleepSysDelta: 3,
      poorSleepDiaDelta: 2,
      time: { hour: 8, minute: 15 },
    },
    weight: {
      lbStart: 182,
      lbEnd: 183,
      follow: 0.24,
      sd: 0.42,
      workoutFactor: 0.35,
      time: { hour: 7, minute: 22 },
    },
    steps: {
      baseStart: 6200,
      baseEnd: 7000,
      sd: 1900,
      workoutBonus: 800,
      time: { hour: 21, minute: 15 },
    },
    exercise: {
      weekdays: [1, 4], // Mon/Thu
      activities: ["Walk", "Strength", "Cycling"],
      durationStart: 22,
      durationEnd: 35,
      sdMinutes: 15,
      caloriesPerMin: 6.6,
      easyPct: 0.26,
      hardPct: 0.1,
      maxWorkoutsPerDay: 1,
      startHour: 16,
      startMinute: 30,
    },
  },
});

export const SAMPLE_PROFILE_IDS = Object.freeze(Object.keys(SAMPLE_PROFILES));
const SAMPLE_PROFILE_ID_SET = new Set(SAMPLE_PROFILE_IDS);
export function isSampleProfileId(profileId) {
  return typeof profileId === "string" && SAMPLE_PROFILE_ID_SET.has(profileId);
}
